// Generates supabase/seed.sql from src/lib/data/seed.ts so the demo adapter and the
// Postgres seed never drift. Run: npm run seed:sql (Node 22+)
import { writeFileSync } from 'node:fs'
import { buildSeed } from '../src/lib/data/seed.ts'
import type { TableName } from '../src/lib/types.ts'

// Parents before children so foreign keys resolve.
const ORDER: TableName[] = [
  'vessels',
  'recipes',
  'package_profiles',
  'batches',
  'batch_ingredients',
  'yeasts',
  'batch_events',
  'batch_measurements',
  'batch_transfers',
  'nutrient_additions',
  'stabilizations',
  'backsweetening_events',
  'packaging_events',
  'tastings',
  'reminders',
]

function lit(v: unknown): string {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  if (Array.isArray(v) || typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
  return `'${String(v).replace(/'/g, "''")}'`
}

const snap = buildSeed()
const out: string[] = ['-- Generated by scripts/gen-seed-sql.ts. Do not edit by hand.', 'begin;']
for (const table of ORDER) {
  const rows = snap[table] as Record<string, unknown>[]
  if (!rows.length) continue
  const cols = Object.keys(rows[0])
  out.push(`\ninsert into ${table} (${cols.join(', ')}) values`)
  out.push(rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(', ')})`).join(',\n') + '\non conflict (id) do nothing;')
}
out.push('commit;')
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n') + '\n')
console.log('wrote supabase/seed.sql')
